var-som_sign_image: make LOADADDR as parameter
Since LOADADDR can change between different U-Boot releases, make it a parameter
to avoid mismatch between kernel signing LOADADDR with U-Boot loadaddr.

For example testing HAB on 6UL/6ULL with U-Boot release lf_v2024.04_6.6.52-2.2.2_var01, the
default LOADADDR must be changed from 0x82000000 to 0x80800000.
This can be done by:
  SOC=mx6ull LOADADDR=0x80800000 ./var-som_sign_image.sh SPL u-boot-ivt.img zImage

Using 0x80800000 as the kernel signing load address for mx6ul/mx6ull to match
U-Boot's default loadaddr, keeps the HAB IVT addresses consistent with
the actual DDR load location avoiding the following error:
  Authenticate image from DDR location 0x80800000...
  Error: Invalid IVT structure

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>